# Generated by Django 4.1 on 2022-09-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='Тэг')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user_ticket', models.CharField(max_length=30, verbose_name='Имя')),
                ('email_user_ticket', models.EmailField(max_length=30, verbose_name='Email')),
                ('time_go', models.DateField(verbose_name='Дата вылета')),
                ('time_back', models.DateField(verbose_name='Дата прилета')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=30, verbose_name='Имя')),
                ('email_user', models.EmailField(max_length=30, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Данные')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('is_working', models.BooleanField(default=True, verbose_name='Публикация')),
                ('free_places', models.IntegerField(verbose_name='Кол-во мест')),
                ('price_econom', models.IntegerField(default=100, verbose_name='Цена Эконома')),
                ('price_standart', models.IntegerField(default=150, verbose_name='Цена Стандарта')),
                ('price_business', models.IntegerField(default=200, verbose_name='Цена Бизнеса')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_hotel.city', verbose_name='Город')),
                ('tags', models.ManyToManyField(to='my_hotel.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_hotel.hotels', verbose_name='Город')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_hotel.country', verbose_name='Город'),
        ),
    ]
