# Generated by Django 4.1 on 2022-09-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='choose',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Эконом Вариант'), (2, 'Стандартный Номер'), (3, 'Бизнес люкс')], default=1, verbose_name='choose'),
            preserve_default=False,
        ),
    ]
