# Generated by Django 4.1 on 2022-08-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_hotel.country', verbose_name='Город')),
            ],
        ),
    ]
