# Generated by Django 4.1 on 2022-08-10 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Данные')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('is_working', models.BooleanField(default=True, verbose_name='Публикация')),
                ('free_places', models.IntegerField(verbose_name='Кол-во мест')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_hotel.city', verbose_name='Город')),
            ],
        ),
    ]
