# Generated by Django 4.1 on 2022-09-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0003_alter_ticket_choose'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('pay_method', models.CharField(max_length=15)),
                ('amount', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
            ],
        ),
    ]
