# Generated by Django 4.1 on 2022-08-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0003_hotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_hotel.hotels', verbose_name='Город')),
            ],
        ),
    ]
