# Generated by Django 4.1 on 2022-08-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0005_tag_hotels_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=255, verbose_name='Тэг'),
        ),
    ]
