# Generated by Django 4.0.6 on 2022-08-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0007_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_user',
            field=models.EmailField(max_length=30, verbose_name='Email'),
        ),
    ]
