# Generated by Django 4.1 on 2022-08-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0008_alter_users_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='Price_business',
            field=models.IntegerField(default=200, verbose_name='Цена Бизнеса'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='price_econom',
            field=models.IntegerField(default=100, verbose_name='Цена Эконома'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='price_standart',
            field=models.IntegerField(default=150, verbose_name='Цена Стандарта'),
        ),
    ]
