# Generated by Django 4.1 on 2022-09-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0011_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='email_user',
            new_name='email_user_ticket',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='name_user',
            new_name='name_user_ticket',
        ),
    ]
